site_name: KillerTools
site_description: A modern, cross-platform Swiss-army toolkit for developers and makers
site_author: Silas Renner (VoxHash)
site_url: https://voxhash.github.io/KillerTools

repo_name: VoxHash/KillerTools
repo_url: https://github.com/VoxHash/KillerTools
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    logo: assets/icons/killer.svg
    favicon: assets/icons/killer.ico

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - User Guide:
    - CLI: cli.md
    - TUI: tui.md
    - GUI: gui.md
  - Plugins:
    - Files: plugins/files.md
    - Crypto: plugins/crypto.md
    - DevTools: plugins/devtools.md
    - Media: plugins/media.md
    - Network: plugins/network.md
    - AI: plugins/ai.md
  - Development:
    - Creating Plugins: development/plugins.md
    - Contributing: development/contributing.md
    - API Reference: development/api.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VoxHash
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VoxHash
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/voxhash
    - icon: fontawesome/brands/telegram
      link: https://t.me/VoxHash
  version:
    provider: mike
